# docker-compose wordpress quick start
version: "3"
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    #image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    # image: mysql:latest
    image: mysql:8.0.27
    container_name: $PROJECT_NAME-db
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - [PROJECT_PATH]/db:/var/lib/mysql
    restart: always
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    expose:
      - 3306
    networks:
      - $NETWORK_NAME

  wordpress:
    image: wordpress:latest
    container_name: $PROJECT_NAME-wordpress
    depends_on:
        - db
    ports:
      - 8081:80
    volumes:
       - [PROJECT_PATH]/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
       - [PROJECT_PATH]/html:/var/www/html
    restart: always
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    networks:
      - $NETWORK_NAME

  wordpress-pma:
    image: phpmyadmin/phpmyadmin
    container_name: $PROJECT_NAME-pma
    depends_on:
        - db
    environment:
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_ARBITRARY=1
    ports:
        - 8082:80
    restart: always
    networks:
      - $NETWORK_NAME

networks:
  $NETWORK_NAME:
    driver: bridge
