# docker-compose wordpress quick start
version: "3"
services:
  db:
    # mariadb image supports both amd64 & arm64 architecture
    #image: mariadb:10.6.4-focal
    # If you want to use MySQL, uncomment the following line
    # image: mysql:latest
    image: mysql:8.0.27
    container_name: [CONTAINER_NAME-db] #CONTAINER_NAME
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - [PROJECT_PATH]/db:/var/lib/mysql #PROJECT_PATH
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=[ROOT_PASSWORD] #DATABASE_ROOT_PASSWORD
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=[DATABASE_PASSWORD] #DATABASE_PASSWORD
    expose:
      - 3306
    networks:
      - [PROJECT-network] #PROJECT_NETWORK

  wordpress:
    image: wordpress:latest
    container_name: [CONTAINER_NAME-wordpress] #CONTAINER_NAME
    depends_on:
        - db
    ports:
      - 8081:80 #PROJECT_ACCESS_PORT
    volumes:
       - [PROJECT_PATH]/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini #PROJECT_PATH
       - [PROJECT_PATH]/html:/var/www/html #PROJECT_PATH
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=[DATABASE_PASSWORD] #DATABASE_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    networks:
      - [PROJECT-network] #PROJECT_NETWORK

  wordpress-pma:
    image: phpmyadmin/phpmyadmin
    container_name: [CONTAINER-pma] #CONTAINER_NAME
    depends_on:
        - db
    environment:
        - PMA_HOST=db
        - PMA_PORT=3306
        - PMA_ARBITRARY=1
    ports:
        - 8082:80
    restart: always
    networks:
      - [PROJECT-network] #PROJECT_NETWORK

networks:
  [PROJECT-network]: #PROJECT_NETWORK
    driver: bridge